"""empty message

Revision ID: 185ee9339ae0
Revises: 564c2b69a746
Create Date: 2021-05-31 12:47:00.367578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '185ee9339ae0'
down_revision = '564c2b69a746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
