"""empty message

Revision ID: 6a43b76ce394
Revises: 5d4f83fbfee1
Create Date: 2021-05-28 18:01:10.538353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a43b76ce394'
down_revision = '5d4f83fbfee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bank_account', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('loan', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('dues', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('payments', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('balance', sa.String(length=80), nullable=False))
    op.drop_index('email', table_name='user')
    op.drop_index('email_2', table_name='user')
    op.create_unique_constraint(None, 'user', ['bank_account'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email_2', 'user', ['email'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_column('user', 'balance')
    op.drop_column('user', 'payments')
    op.drop_column('user', 'dues')
    op.drop_column('user', 'loan')
    op.drop_column('user', 'bank_account')
    # ### end Alembic commands ###
